// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgLEc6NjgAybxNG3-z4OhQ1HIeqKhaBM8',
    appId: '1:595846667553:web:ff60db898afaf6462e7260',
    messagingSenderId: '595846667553',
    projectId: 'bloodapp-4a264',
    authDomain: 'bloodapp-4a264.firebaseapp.com',
    storageBucket: 'bloodapp-4a264.appspot.com',
    measurementId: 'G-BP6CF7LT0V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnim22Mvvq9cv8JJZR1VCybtW7Puq044M',
    appId: '1:595846667553:android:50e70f292fbe428c2e7260',
    messagingSenderId: '595846667553',
    projectId: 'bloodapp-4a264',
    storageBucket: 'bloodapp-4a264.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4PpVE-I9VskQmFCsLzycztNVgNRihaZs',
    appId: '1:595846667553:ios:c190f85ba0d6f5542e7260',
    messagingSenderId: '595846667553',
    projectId: 'bloodapp-4a264',
    storageBucket: 'bloodapp-4a264.appspot.com',
    iosBundleId: 'com.example.pulsepoint',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4PpVE-I9VskQmFCsLzycztNVgNRihaZs',
    appId: '1:595846667553:ios:c190f85ba0d6f5542e7260',
    messagingSenderId: '595846667553',
    projectId: 'bloodapp-4a264',
    storageBucket: 'bloodapp-4a264.appspot.com',
    iosBundleId: 'com.example.pulsepoint',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgLEc6NjgAybxNG3-z4OhQ1HIeqKhaBM8',
    appId: '1:595846667553:web:708565bda651e89d2e7260',
    messagingSenderId: '595846667553',
    projectId: 'bloodapp-4a264',
    authDomain: 'bloodapp-4a264.firebaseapp.com',
    storageBucket: 'bloodapp-4a264.appspot.com',
    measurementId: 'G-B2ZYJYSLNE',
  );

}